### ISSUE TITLE
Cannot use yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by cinghie** [skeeks-semenov/yii2-ckeditor#2]
On php 7.2

PHP Fatal error:  Cannot use yii\base\Object as Object because 'Object' is a special class name in ...vendor\skeeks\yii2-ckeditor\src\CKEditorPresets.php on line 11

To solve it:

in CKEditorPresets.php

`use yii\base\Object as baseObject;

class CKEditorPresets extends baseObject`

**Comment by skeeks-semenov** [comment]
https://github.com/skeeks-semenov/yii2-ckeditor/pull/3
